// Generated by CoffeeScript 1.8.0
(function() {
  var Workspace;

  window.app = window.app || {};

  Workspace = Backbone.Router.extend({
    routes: {
      '*filter': 'setFilter'
    },
    setFilter: function(param) {
      if (param) {
        param = param.trim();
      }
      window.app.TodoFilter = param || '';
      return app.Todos.trigger('filter');
    }
  });

  window.app.TodoRouter = new Workspace();

  Backbone.history.start();

}).call(this);

//# sourceMappingURL=router.js.map
