// Generated by CoffeeScript 1.8.0
(function() {
  window.app = window.app || {};

  window.ENTER_KEY = 13;

  $(function() {
    return new app.AppView();
  });

}).call(this);

//# sourceMappingURL=app.js.map
