// Generated by CoffeeScript 1.8.0
(function() {
  window.app = window.app || {};

  window.app.TodoView = Backbone.View.extend({
    tagName: 'li',
    template: _.template($('#item-template').html()),
    events: {
      'click .toggle': 'togglecompleted',
      'dblclick label': 'edit',
      'click .destroy': 'clear',
      'keypress .edit': 'updateOnEnter',
      'blur .edit': 'close'
    },
    initialize: function() {
      this.listenTo(this.model, 'change', this.render);
      this.listenTo(this.model, 'destroy', this.remove);
      return this.listenTo(this.model, 'visible', this.toggleVisible);
    },
    render: function() {
      if (this.model.changed.id !== void 0) {
        return;
      }
      this.$el.html(this.template(this.model.toJSON()));
      this.$el.toggleClass('completed', this.model.get('completed'));
      this.toggleVisible();
      this.$input = this.$('.edit');
      return this;
    },
    toggleVisible: function() {
      return this.$el.toggleClass('hidden', this.isHidden());
    },
    isHidden: function() {
      var isCompleted;
      isCompleted = this.model.get('completed');
      return (!isCompleted && app.TodoFilter === 'completed') || (isCompleted && app.TodoFilter === 'active');
    },
    togglecompleted: function() {
      return this.model.toggle();
    },
    edit: function() {
      this.$el.addClass('editing');
      return this.$input.focus();
    },
    close: function() {
      var value;
      value = this.$input.val().trim();
      if (value) {
        this.model.save({
          title: value
        });
      }
      return this.$el.removeClass('editing');
    },
    updateOnEnter: function(e) {
      if (e.which === ENTER_KEY) {
        return this.close();
      }
    },
    clear: function() {
      return this.model.destroy();
    }
  });

}).call(this);

//# sourceMappingURL=todos.js.map
